language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install pytest

script:
  - pytest tests --cov=api tests/

after_success:
- coveralls